version: '3'
services:
    gobot:
        build: 
          context: ./CandallGo
          dockerfile: dockerfile
        container_name: candall-go-bot
        restart: always
        env_file:
          - .env
        depends_on:
          - postgres
          - vector
        networks:
          - postgres-network
          - logging
    bot:
        build: 
          context: .
          dockerfile: dockerfile
        container_name: candall-bot
        restart: always
        volumes:
          - ./app-volume:/usr/app/src
        depends_on:
          - postgres
        networks:
          - postgres-network

    postgres:
        container_name: candall-postgres
        image: postgres:latest
        restart: always
        #command: -c ssl=on -c ssl_cert_file=/etc/ssl/certs/ssl-cert-snakeoil.pem -c ssl_key_file=/etc/ssl/private/ssl-cert-snakeoil.key
        environment:
          POSTGRES_DB: postgres
          POSTGRES_USER: vladmin
          POSTGRES_PASSWORD: vladik
          PGDATA: /var/lib/postgresql/data
        volumes:
          - ./data:/var/lib/postgresql/data
        ports:
          - '5432:5432'
        networks:
          -  postgres-network

    pgadmin4:
        container_name: candall-pgadmin
        image: dpage/pgadmin4:latest
        restart: always
        environment:
          PGADMIN_DEFAULT_EMAIL: vladkorolev280@gmail.com
          PGADMIN_DEFAULT_PASSWORD: vladik
          PGADMIN_LISTEN_PORT: 8080
        ports:
          - "8080:8080"
        volumes:
          - ./servers.json:/pgadmin4/servers.json
        networks:
          - postgres-network
        depends_on:
          - postgres

    opensearch:
        container_name: opensearch
        image: opensearchproject/opensearch:2.12.0
        environment:
          - discovery.type=single-node
          - DISABLE_SECURITY_PLUGIN=true 
          - bootstrap.memory_lock=true
          - OPENSEARCH_JAVA_OPTS=-Xms512m -Xmx512m
        ulimits:
          memlock:
            soft: -1
            hard: -1
        volumes:
          - opensearch-data:/usr/share/opensearch/data
        ports:
          - "9200:9200"
        networks:
          - logging

    dashboards:
      image: opensearchproject/opensearch-dashboards:2.12.0
      ports:
        - "5601:5601"
      environment:
        - OPENSEARCH_HOSTS=["http://opensearch:9200"]
        - DISABLE_SECURITY_DASHBOARDS_PLUGIN=true
      depends_on:
        - opensearch
      networks:
        - logging

    vector:
      container_name: vector
      image: timberio/vector:0.41.0-alpine
      environment:
        - VECTOR_LOG=debug
      volumes:
        - ./vector/vector.yaml:/etc/vector/vector.yaml:ro
      depends_on:
        - opensearch
      networks:
        - logging
      ports:
        - "9000:9000"

volumes:
  opensearch-data:

networks:
  logging:
    driver: bridge
  postgres-network:
    driver: bridge
